import { CATEGORY_LABELS, EQUIVALENTS } from '@carbonwise/shared';
import type { Request, Response } from 'express';
import PDFDocument from 'pdfkit';

import { queryOne } from '../../config/database';
import { asyncHandler, AppError } from '../../middleware/error-handler.middleware';
import * as carbonRepo from '../carbon/carbon.repository';

/**
 * PDF Report Generator using PDFKit.
 * Generates sustainability reports with current footprint,
 * historical comparison, reduction %, and AI recommendations.
 */

export const generate = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const userId = req.userId!;
  const from = req.query.from as string || new Date(Date.now() - 30 * 86400000).toISOString().split('T')[0]!;
  const to = req.query.to as string || new Date().toISOString().split('T')[0]!;

  // Gather data
  const user = await queryOne<{ name: string; email: string; eco_score: number; level: number }>(
    'SELECT name, email, eco_score, level FROM users WHERE id = $1', [userId],
  );
  if (!user) throw new AppError(404, 'NOT_FOUND', 'User not found');

  const [totalKg, categorySummary, dailyTotals] = await Promise.all([
    carbonRepo.getTotalEmissions(userId, from, to),
    carbonRepo.getCategorySummary(userId, from, to),
    carbonRepo.getDailyTotals(userId, from, to),
  ]);

  // Generate PDF
  const doc = new PDFDocument({ size: 'A4', margin: 50 });

  // Set response headers for PDF download
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=carbonwise-report-${from}-to-${to}.pdf`);

  doc.pipe(res);

  // ---- Header ----
  doc
    .fontSize(28)
    .fillColor('#10b981')
    .text('CarbonWise', { align: 'center' })
    .moveDown(0.3);

  doc
    .fontSize(14)
    .fillColor('#6b7280')
    .text('Sustainability Report', { align: 'center' })
    .moveDown(0.5);

  doc
    .fontSize(10)
    .fillColor('#9ca3af')
    .text(`Generated for: ${user.name} | Period: ${from} to ${to}`, { align: 'center' })
    .text(`Generated on: ${new Date().toLocaleDateString()}`, { align: 'center' })
    .moveDown(1.5);

  // ---- Summary Section ----
  doc
    .fontSize(18)
    .fillColor('#1f2937')
    .text('📊 Carbon Footprint Summary')
    .moveDown(0.5);

  doc
    .fontSize(12)
    .fillColor('#374151')
    .text(`Total Emissions: ${totalKg.toFixed(2)} kg CO₂e`)
    .text(`Equivalent Trees Needed: ${(totalKg / EQUIVALENTS.KG_PER_TREE_PER_YEAR).toFixed(1)}`)
    .text(`Eco Score: ${user.eco_score} | Level: ${user.level}`)
    .moveDown(1);

  // ---- Category Breakdown ----
  doc
    .fontSize(18)
    .fillColor('#1f2937')
    .text('📂 Breakdown by Category')
    .moveDown(0.5);

  for (const cat of categorySummary) {
    const catKg = parseFloat(String(cat.total_kg));
    const pct = totalKg > 0 ? ((catKg / totalKg) * 100).toFixed(1) : '0';
    const label = CATEGORY_LABELS[cat.category] ?? cat.category;
    doc
      .fontSize(11)
      .fillColor('#374151')
      .text(`  • ${label}: ${catKg.toFixed(2)} kg CO₂e (${pct}%)`);
  }
  doc.moveDown(1);

  // ---- Daily Trend ----
  doc
    .fontSize(18)
    .fillColor('#1f2937')
    .text('📈 Daily Emissions Trend')
    .moveDown(0.5);

  const maxKg = Math.max(...dailyTotals.map((d) => parseFloat(String(d.total_kg))), 1);
  const barWidth = 400;
  const barHeight = 12;

  for (const day of dailyTotals.slice(-15)) { // Last 15 days
    const kg = parseFloat(String(day.total_kg));
    const width = (kg / maxKg) * barWidth;
    const y = doc.y;

    doc.fontSize(8).fillColor('#6b7280').text(`${day.entry_date}`, 50, y, { width: 80 });
    doc.rect(135, y, width, barHeight).fill('#10b981');
    doc.fontSize(8).fillColor('#374151').text(`${kg.toFixed(1)} kg`, 135 + width + 5, y);
    doc.y = y + barHeight + 4;
  }
  doc.moveDown(1);

  // ---- Recommendations ----
  doc
    .fontSize(18)
    .fillColor('#1f2937')
    .text('💡 Recommendations')
    .moveDown(0.5);

  const tips = [
    'Consider using public transport for your daily commute',
    'Switching to LED lighting can reduce electricity emissions by 15%',
    'Try incorporating more plant-based meals into your diet',
    'Reduce single-use plastic by carrying reusable bags and bottles',
    'Unplug electronics when not in use to save standby power',
  ];

  for (const tip of tips) {
    doc.fontSize(11).fillColor('#374151').text(`  ✅ ${tip}`);
  }
  doc.moveDown(1);

  // ---- Footer ----
  doc
    .fontSize(8)
    .fillColor('#9ca3af')
    .text('Generated by CarbonWise — AI-Powered Carbon Intelligence Platform', { align: 'center' })
    .text('Data sources: EPA, DEFRA, IPCC 2023', { align: 'center' });

  doc.end();
});
